version: '2'
services:
  php:
    depends_on:
      - mariadb
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=dev
      - BENCHMARK_CASE=mysql

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=event_store_adapter_benchmarks
