version: '2'
services:
  php:
    depends_on:
      - percona
    environment:
      - MYSQL_HOST=percona
      - MYSQL_ROOT_PASSWORD=dev
      - BENCHMARK_CASE=mysql

  percona:
    image: percona
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=event_store_adapter_benchmarks
