version: '2'
services:
  php:
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - BENCHMARK_CASE=mongodb

  mongodb:
      image: mongo
      ports:
        - 27017:27017
